services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/carles_landsurveys?useSSL=false&serverTimezone=UTC
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      SS_USERNAME: matbena
      SS_PASSWORD: 5432
      PRIVATE_KEY: ec9f712b405cbf435bb10e567bd56381b8d97431727abaf5cd3c730f8e8b8fc1
      USER_GENERATOR: MATBENA
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: carles_landsurveys
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Restore your database

volumes:
  postgres_data: